server.port=${PORT:8080}

spring.application.name=omtb-backend
spring.data.mongodb.uri=mongodb+srv://gobinath:gobiuk008@cluster0.ijicqda.mongodb.net/MTBS?appName=Cluster0

app.jwt.secret=YUFay20uW0ytzRJ0EZ5Ha5CXepvfwgeRIXuXvJYGh7x
app.jwt.expirationMs=86400000

app.cloudinary.cloud-name=dzruly004
app.cloudinary.api-key=719262987377642
app.cloudinary.api-secret=MKMxmgwUj3U8fkpVIBcuhAZ4_AI

app.cors.allowed-origins=http://localhost:3000
